language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install:
  - pip install .[develop]

# command to run tests
script:
  - flake8
  - py.test test.py
